import { SITE_URL } from "~/lib/site";
import type { DiagramReadout } from "~/features/diagram/readout";

// The Markdown twin of /{owner}/{repo} that agents read: served at
// /{owner}/{repo}.md, and at the page URL itself for `Accept: text/markdown`.

function repositoryUrls(owner: string, repo: string) {
  const path = `/${encodeURIComponent(owner.toLowerCase())}/${encodeURIComponent(repo.toLowerCase())}`;
  return {
    page: `${SITE_URL}${path}`,
    github: `https://github.com/${owner}/${repo}`,
  };
}

/** A fence longer than any backtick run inside, so the block cannot end early. */
function fence(content: string): string {
  const longest = Math.max(
    2,
    ...Array.from(content.matchAll(/`+/g), (match) => match[0].length),
  );
  return "`".repeat(longest + 1);
}

/** One line of text (agents read the raw Markdown, so nothing is escaped). */
function inline(value: string): string {
  return value.replace(/\s+/g, " ").trim();
}

function formatDay(value: string | null): string | null {
  const time = value ? Date.parse(value) : NaN;
  return Number.isFinite(time)
    ? new Date(time).toISOString().slice(0, 10)
    : null;
}

export function repositoryMarkdown(params: {
  owner: string;
  repo: string;
  diagram: string;
  readout: DiagramReadout;
  /** The watch page, when a video tour of the repository exists. */
}): string {
  const { owner, repo, diagram, readout } = params;
  const name = `${owner}/${repo}`;
  const urls = repositoryUrls(owner, repo);
  const day = formatDay(readout.lastSuccessfulAt);
  const lines: string[] = [
    `# ${inline(name)} architecture`,
    "",
    `> Architecture diagram of the GitHub repository ${inline(name)}, generated by diagram studio from its file tree, README and a sample of source files${day ? ` (last updated ${day})` : ""}. It is an AI-made overview: check details against the source.`,
    "",
    `- Interactive diagram: ${urls.page}`,
    `- Repository: ${urls.github}`,
    "",
  ];

  if (readout.explanation) {
    // Its own headings nest under "Overview".
    const overview = readout.explanation
      .trim()
      .replace(
        /^(#{1,6})\s+/gm,
        (_, level: string) => `${"#".repeat(Math.min(6, level.length + 2))} `,
      );
    lines.push("## Overview", "", overview, "");
  }

  const mermaidFence = fence(diagram);
  lines.push(
    "## Diagram (Mermaid)",
    "",
    `${mermaidFence}mermaid`,
    diagram.trim(),
    mermaidFence,
    "",
  );

  if (readout.groups.length) {
    lines.push("## Components", "");
    for (const group of readout.groups) {
      lines.push(`### ${inline(group.label)}`, "");
      if (group.description) lines.push(inline(group.description), "");
      for (const component of group.components) {
        const label = component.href
          ? `[${inline(component.label)}](${component.href})`
          : `**${inline(component.label)}**`;
        const details = [
          component.type !== "component" ? inline(component.type) : null,
          component.description ? inline(component.description) : null,
          component.path ? `\`${component.path.replace(/`/g, "")}\`` : null,
        ].filter(Boolean);
        lines.push(
          `- ${label}${details.length ? `: ${details.join(" · ")}` : ""}`,
        );
      }
      lines.push("");
    }
  }

  if (readout.connections.length) {
    lines.push("## Connections", "");
    for (const connection of readout.connections) {
      const what = [connection.label, connection.description]
        .filter((value): value is string => Boolean(value))
        .map(inline)
        .join(" · ");
      const evidence = connection.evidencePath
        ? ` (evidence: \`${connection.evidencePath.replaceAll("`", "")}\`)`
        : "";
      lines.push(
        `- ${inline(connection.from)} → ${inline(connection.to)}${what ? `: ${what}` : ""}${evidence}`,
      );
    }
    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

/** What an agent gets for a repository with no stored public diagram. */
export function missingDiagramMarkdown(owner: string, repo: string): string {
  const name = `${owner}/${repo}`;
  const urls = repositoryUrls(owner, repo);
  return [
    `# ${inline(name)} architecture`,
    "",
    `Diagram studio has no stored diagram of ${inline(name)} yet.`,
    "",
    `To make one, open ${urls.page} in a browser: the page generates the diagram (about a minute), stores it, and this Markdown then describes it. Private repositories need the owner's GitHub token and are never served here.`,
    "",
    `- Repository: ${urls.github}`,
    `- How the studio works: ${SITE_URL}/llms.txt`,
    "",
  ].join("\n");
}
